### ISSUE TITLE
Signing up

### ISSUE THREAD

**Issue by eugeniaguerrero** [emmpak/EEEKbnb#1]
As an owner
So that I can list a new space
I would like to sign up

**Comment by eugeniaguerrero** [comment]
Need to create database to store new user details

**Comment by emmpak** [comment]
scenario 'without entering a first name'
scenario 'without entering a last name'
scenario 'without entering an email'
scenario 'with an invalid email'
scenario 'with an existing email'

**Comment by exchai93-zz** [comment]
bcrypt password
