### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by eugeniaguerrero** [emmpak/EEEKbnb#2]
As an owner
So that I can go into my profile
I want to be able to log in

**Comment by exchai93-zz** [comment]
potential log in errors? 

scenario 'without entering an email'
scenario 'with an invalid email'
scenario 'with an invalid password'

**Comment by exchai93-zz** [comment]
check session id is OK when logging in

**Comment by exchai93-zz** [comment]
AND LOG OUT??

**Comment by exchai93-zz** [comment]
helpers do

    def empty_params
      if params[:email].empty? || params[:password].empty?
        flash.next[:error] = "Please enter an email and password"
        redirect '/sessions/new'
      end
    end

**Comment by exchai93-zz** [comment]
needs to display flash error when user is logged in and attempts to log in again
