### ISSUE TITLE
Advertising spaces

### ISSUE THREAD

**Issue by eugeniaguerrero** [emmpak/EEEKbnb#5]
As an owner
So that I can advertise my space/spaces
I would like to provide details of the name, description, and price per night of stay

**Comment by eugeniaguerrero** [comment]
Need to let the listings be visible without logging in

**Comment by exchai93-zz** [comment]
list of apartments is on the homepage

**Comment by exchai93-zz** [comment]
save information to the database
page to show whatever is saved in the database
